[package]
name = "os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 0
panic = "abort"
lto = false

[profile.release]
opt-level = 3
panic = "abort"
lto = true
codegen-units = 1
